### ISSUE TITLE
publishConfig in package.json prevents publishing to local repositories

### ISSUE THREAD

**Issue by yrtimiD** [juliangruber/builtins#16]
Your package.json has next block:
`"publishConfig": {
    "registry": "https://registry.npmjs.org"
  }`

As I just discovered, it overrides any repository configurations configured in my .npmrc file, which prevents me from publishing this package to our internal corporate repository.
If these values are not 100% necessary for you, can you remove it? Global npmjs.org is always used by default anyway.

**Comment by juliangruber** [comment]
no problem!
