### ISSUE TITLE
Support mode to get all Builtins for any version of npm

### ISSUE THREAD

**Issue by rzhade3** [juliangruber/builtins#47]
It'd be useful to have a mode (`version_agnostic: true`?) that'll return all builtin modules that have existed for any version of npm. 

For example, with this mode, we'd return `freelist`, `v8`, `process` and `inspector`, regardless of the version of node that we're using to run `builtins`. 

If you're OK with this feature request, I'd be happy to take a crack at implementing it.

**Comment by juliangruber** [comment]
sounds good to me, please go ahead :) I'd propose instead of adding an option we support `version: '*'`, and change the internal semver checks. I think that would be the most elegant, if it's not too complex to implement
