### ISSUE TITLE
Strategy for supporting multiple node-versions?

### ISSUE THREAD

**Issue by voxpelli** [juliangruber/builtins#7]
Would be nice to have a way to define what node-version built-ins one want to fetch – especially now when we have `0.10`, `0.12` and io.js `1.x` out there.

I came across this module as the [Dependency Check](https://github.com/maxogden/dependency-check) module uses it and in that scenario, where you want to check whether a module is a built in one or not, it is pretty important to know which Node version of builtins one is matching against.

**Comment by juliangruber** [comment]
is this a problem yet, ie did this cause a bug?

**Comment by voxpelli** [comment]
I haven't run into the problem yet, but eg the `smalloc` moduleis only available in Node 0.12 and io.js 1.x – not in Node 0.10

**Comment by juliangruber** [comment]
If `smalloc` isn't available in node 0.10, but a module depends on it, doesn't that mean that the module won't run 0.10 and thus is considered broken for that version?

**Comment by voxpelli** [comment]
@juliangruber: Exactly :) And such mistakes is what one can eg. use Dependency Check to find

**Comment by juliangruber** [comment]
Aaah ok now I understand. Yeah, it would be cool to store one `bultins.json` per node version and have an api like `var builtins = require('builtins')(version)` which defaults to `process.version`.

**Comment by watson** [comment]
@juliangruber since there have been a few new modules added to Node core lately this would be really nice to have. I can make a PR if you like?

**Comment by juliangruber** [comment]
> @juliangruber since there have been a few new modules added to Node core lately this would be really nice to have. I can make a PR if you like?

yes please very much! :)
